Categories:
  - Security
License: GPL-3.0-only
AuthorName: Fatih İlhan
WebSite: https://github.com/seralifatih/OneRule
SourceCode: https://github.com/seralifatih/OneRule
IssueTracker: https://github.com/seralifatih/OneRule/issues
Changelog: https://github.com/seralifatih/OneRule/releases

AutoName: OneRule

RepoType: git
Repo: https://github.com/seralifatih/OneRule.git

Builds:
  - versionName: 2.0.2
    versionCode: 12
    commit: 2.0.2
    output: build/app/outputs/flutter-apk/app-release.apk
    srclibs:
      - flutter@3.41.4
    rm:
      - ios
      - linux
      - macos
      - windows
    prebuild: echo "flutter.sdk=$$flutter$$" > android/local.properties && $$flutter$$/bin/flutter
      config --no-analytics && $$flutter$$/bin/flutter pub get
    scandelete:
      - .pub-cache
    build: $$flutter$$/bin/flutter build apk --release --no-pub

AutoUpdateMode: Version
UpdateCheckMode: Tags
UpdateCheckData: pubspec.yaml|version:\s.+\+(\d+)|.|version:\s(.+)\+
CurrentVersion: 2.0.2
CurrentVersionCode: 12
