Categories:
  - Security

License: GPL-3.0-only

AuthorName: Fatih İlhan
WebSite: https://github.com/seralifatih/OneRule
SourceCode: https://github.com/seralifatih/OneRule
IssueTracker: https://github.com/seralifatih/OneRule/issues
Changelog: https://github.com/seralifatih/OneRule/releases

AutoName: OneRule

RepoType: git
Repo: https://github.com/seralifatih/OneRule.git

Builds:
  - versionName: "2.0.0"
    versionCode: 10
    commit: "2.0.0"
    srclibs:
      - flutter@stable
    rm:
      - ios
      - linux
      - macos
      - web
      - windows
    prebuild:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - export PATH="$PATH:$$flutter$$/bin"
      - flutter config --no-analytics
      - flutter pub get
    build:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - export PATH="$PATH:$$flutter$$/bin"
      - flutter config --no-analytics
      - flutter build apk --release
    output: build/app/outputs/flutter-apk/app-release.apk

AutoUpdateMode: Version
UpdateCheckMode: Tags
UpdateCheckData: pubspec.yaml|version:\s.+\+(\d+)|.|version:\s(.+)\+

CurrentVersion: "2.0.0"
CurrentVersionCode: 10