# Bellek Ayarları
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Android Ayarları
android.useAndroidX=true
android.enableJetifier=true

# Çökme Önleyici Kritik Ayarlar (Windows + Java 21 için)
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false